### ISSUE TITLE
Failed to load MI command.

### ISSUE THREAD

**Issue by rahulsharma11** [gnu-mcu-eclipse/openocd#14]
Hi, I am trying to debug PIxhawk firmware in Nucleo(STM32f411RE) board through openOCD in Eclipse.
I am using latest openOCD(0.10.0-201704182147), The project is built comfortably but having an issue while debugging it. 
It always throughs an error - 
Failed to execute MI command: ~/build_directory/src/firmware/nuttx/firmware_nuttx.

I didn't get the error while debugging it through command line.
Please suggest any solution.

**Comment by ilg-ul** [comment]
for general support, please use the project forum.
