### ISSUE TITLE
src/flash/nor/Makefile.am lists fespi.c twice

### ISSUE THREAD

**Issue by TM1234** [gnu-mcu-eclipse/openocd#16]
Minor issue but src/flash/nor/Makefile.am lists fespi.c twice - lines 25 and 27:

https://github.com/gnu-mcu-eclipse/openocd/blob/gnu-mcu-eclipse-dev/src/flash/nor/Makefile.am

**Comment by ilg-ul** [comment]
thank you, I'll fix it.

**Comment by TM1234** [comment]
Thanks Liviu.

**Comment by TM1234** [comment]
FYI this issue still persists.

Also src/rtos/Makefile.am lists %D%/riscv_debug.c twice.

**Comment by ilg-ul** [comment]
ah, I misssed it... I'll try to fix it these days.

**Comment by TM1234** [comment]
Thanks. Obviously not critical.

**Comment by ilg-ul** [comment]
not critical, but annoying. 

fixed in https://github.com/gnu-mcu-eclipse/openocd/commit/8721a129e9c45897ff9026d548fc83f2ca4bb7be
