### ISSUE TITLE
St-link/V2

### ISSUE THREAD

**Issue by protodmorgan** [gnu-mcu-eclipse/openocd#28]
Attempting to set this up. openOCD connects just fine, but I get this error when launching the debugger.

Error in services launch sequence
Unhandled exception when executing Sequence org.eclipse.cdt.dsf.gdb.service.command.GDBControl_7_0$1@e24df6, step #0
java.lang.AbstractMethodError

**Comment by ilg-ul** [comment]
Did you also check with the sources compiled from the latest official openocd repository?

**Comment by protodmorgan** [comment]
Brand new setup. So I just downloaded all the latest version etc. However, I wouldn’t rule out it being an issue with Truestudio, but it is based off of eclipse.

**Comment by ilg-ul** [comment]
please do not reply by email.

> I just downloaded all the latest version etc

no, please check other binaries than those downloaded from GNU MCU Eclipse. it might be possible that my binaries to have some problems introduced by te RISC-V code. if with a different distribution it works and with mine it fails, I'll further investigate.

and be sure you run the tests on a fresh Eclipse downloaded from https://github.com/gnu-mcu-eclipse/org.eclipse.epp.packages/releases, not another distribution.

**Comment by protodmorgan** [comment]
Go ahead and close this, I'm chalking it up to Atollic it appears to be running on Neon 1.
