### ISSUE TITLE
How do openocd choose multiple cmsis-dap devices?

### ISSUE THREAD

**Issue by ouki-wang** [gnu-mcu-eclipse/openocd#29]
I use arduino+microbit1+microbit2 to complete this experiment

How do openocd choose multiple cmsis-dap devices?
Via cmsis_dap_serial?
How to get cmsis_dap_serial?
I copied the cmsis_dap_serial of the current connection cmsis-dap from the keil debugging interface, but when the program is burned, I can't find the cmsis-dap device.

**Comment by ilg-ul** [comment]
Do you think this is a GNU MCU Eclipse OpenOCD bug?

**Comment by ouki-wang** [comment]
@ilg-ul 
I have already solved this problem. Serial no must be lowercase, using the serial number of the usb descriptor.

**Comment by ilg-ul** [comment]
ok.
