### ISSUE TITLE
src/target/Makefile.am lists riscv_semihosting.c twice

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/openocd#30]
Minor issue:

src/target/Makefile.am lists riscv_semihosting.c twice:

Here

https://github.com/gnu-mcu-eclipse/openocd/blob/gnu-mcu-eclipse-dev/src/target/Makefile.am#L144

and here: 

https://github.com/gnu-mcu-eclipse/openocd/blob/gnu-mcu-eclipse-dev/src/target/Makefile.am#L147

I'll do a PR for this anon but am in the middle of other stuff so just logging it here so I don't forget it...

**Comment by ilg-ul** [comment]
Oops!

Careless merge... :-(

**Comment by ilg-ul** [comment]
Fixed.

**Comment by TommyMurphyTM1234** [comment]
Thanks a lot Liviu.

**Comment by ilg-ul** [comment]
You're welcome, Tommy.

Thank you for taking the time to report the problems you encounter.
