### ISSUE TITLE
Incompatible date of binaries for macOS

### ISSUE THREAD

**Issue by ivankravets** [gnu-mcu-eclipse/openocd#35]
Hi,

I've just downloaded the latest release `0.10.0-9-20181016-1725` for macOS. However, inside all files are dated by July 24, 2018. Is this OK?

Also, I see that new version does not understand double braces `program {{$SOURCE}}`.

Thanks!

**Comment by ilg-ul** [comment]
>  inside all files are dated by July 24, 2018. Is this OK?

oops! no, it is not ok, I'll rebuild this package.

> I see that new version does not understand double braces `program {{$SOURCE}}`

could you please elaborate?

**Comment by ivankravets** [comment]
> could you please elaborate?

Please ping me here when a new version will be available. Maybe, this issue is already fixed.

**Comment by ilg-ul** [comment]
please check 

https://github.com/gnu-mcu-eclipse/openocd/releases/tag/v0.10.0-10-20181020

**Comment by ivankravets** [comment]
Thanks, binaries look updated.

The issue with `{Curly-Braces} ` still persists. The latest working version is `0.10.0-6-20180112`. We use it in production. 

See docs and "24.4 Tcl Quoting Operators" =>  http://openocd.org/doc/html/Tcl-Crash-Course.html

> {curly-braces} can be nested, single quotes can not. {{{this is nested 3 times}}} 

We use `{curly-braces}` to escape a path which can contain a space. A few examples

* `program {path/contains/some space}` - works with the latest release
* `program {path/contains/some space}` - does not work with `<= 0.10.0-6`
* `program {{path/contains/some space}}` - works with `<= 0.10.0-6`
* `program {path/contains/some space}` - works with the latest release.

Who is a good expert in Tcl? I don't know which behaviour is valid :( Following the official docs, we can use multiple brances without a risk. There is online Tcl compiler, you can try to play with it https://www.tutorialspoint.com/execute_tcl_online.php

```tcl
set testStr {hello {Tcl} world}
puts $testStr
```

which produces
```
hello {Tcl} world
```

Also see `[6]` in http://www.tcl.tk/man/tcl8.5/TclCmd/Tcl.htm

**Comment by ilg-ul** [comment]
ah, tcl... I'm afraid I can't be of much help.

openocd uses jimtcl as a submodule, and I checked, my latest release points to a relatively recent commit of jimtcl (Aug 18).

I suggest you report the problem to the jimtcl project.
