### ISSUE TITLE
Beaglebone Black : IR capture error 

### ISSUE THREAD

**Issue by r00tb3** [gnu-mcu-eclipse/openocd#38]
I'm trying to JTAG BBB using J-Link adapter and I end up facing the following error:

      GNU MCU Eclipse 64-bit Open On-Chip Debugger 0.10.0+dev-00352-gaa6c7e9b (2018-10-20- 
      06:18)
      Licensed under GNU GPL v2
      For bug reports, read
      http://openocd.org/doc/doxygen/bugs.html
      adapter speed: 800 kHz
      trst_and_srst separate srst_gates_jtag trst_push_pull srst_open_drain connect_deassert_srst
      Info : auto-selecting first available session transport "jtag". To override use 'transport select 
      <transport>'.
       Info : Listening on port 6666 for tcl connections
       Info : Listening on port 4444 for telnet connections
       Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46
       Info : Hardware version: 8.00
       Info : VTarget = 3.410 V
       Info : clock speed 800 kHz
       Info : JTAG tap: am335x.jrc tap/device found: 0x2b94402f (mfg: 0x017 (Texas Instruments), part: 
       0xb944, ver: 0x2)
        Info : JTAG tap: auto0.tap tap/device found: 0xffffffff (mfg: 0x7ff (<invalid>), part: 0xffff, ver: 0xf)
       Error: auto0.tap: IR capture error; saw 0x0003 not 0x0001
       Warn : Bypassing JTAG setup events due to errors
       Info : Listening on port 3333 for gdb connections
       Info : Listening on port 3334 for gdb connections

I'm unable to halt the processor after opening up a telent session nor able to do anything else.

After openeing a telenet session.

       Trying 127.0.0.1...
       Connected to localhost.
       Escape character is '^]'.
       Open On-Chip Debugger
       > halt
       Target not examined yet

Where am I going wrong?

**Comment by ilg-ul** [comment]
I don't know. 

Did you try the same sequence of commands with an OpenOCD build from the master and it works?

**Comment by r00tb3** [comment]
@ilg-ul No but as you can see from above I'm using the 2018-10-20 version i think this will be stable.

**Comment by ilg-ul** [comment]
> the 2018-10-20 version i think this will be stable

negative. those versions included some RISC-V code which affected the other targets.

not to mention there is no such thing as a stable OpenOCD version.

try the latest release.

anyway, before reporting problems here be sure they are specific to the GNU MCU Eclipse distribution, which means a similar version built from the master sources works.

if the problem also occurs in the master, please report it to https://sourceforge.net/p/openocd/tickets/

**Comment by r00tb3** [comment]
@ilg-ul Okay!! I'll try the master version and the latest release let you know soon.

Thanks for the response.

**Comment by r00tb3** [comment]
> > the 2018-10-20 version i think this will be stable
> 
> negative. those versions included some RISC-V code which affected the other targets.
> 
> not to mention there is no such thing as a stable OpenOCD version.
> 
> try the latest release.
> 
> anyway, before reporting problems here be sure they are specific to the GNU MCU Eclipse distribution, which means a similar version built from the master sources works.
> 
> if the problem also occurs in the master, please report it to https://sourceforge.net/p/openocd/tickets/

I tried as you said git cloned the master branch built it still gives me the same error.

I don't know where I'm going wrong.

    openocd -v
    Open On-Chip Debugger 0.10.0+dev-00463-g436782b (2019-02-13-22:45)
    Licensed under GNU GPL v2
    For bug reports, read
	  http://openocd.org/doc/doxygen/bugs.html


I'm using the following cfg files:--

    sudo openocd -f /interface/jlink.cfg -f /board/ti_beaglebone_black.cfg
    Open On-Chip Debugger 0.10.0+dev-00463-g436782b (2019-02-13-22:45)
    Licensed under GNU GPL v2
    For bug reports, read
	   http://openocd.org/doc/doxygen/bugs.html
    adapter speed: 1000 kHz
    trst_and_srst separate srst_gates_jtag trst_push_pull srst_open_drain connect_deassert_srst
    Info : auto-selecting first available session transport "jtag". To override use 'transport  select 
    <transport>'.
    Info : Listening on port 6666 for tcl connections
    Info : Listening on port 4444 for telnet connections
    Info : J-Link ARM V8 compiled Nov 28 2014 13:44:46
    Info : Hardware version: 8.00
    Info : VTarget = 2.426 V
    Info : clock speed 1000 kHz
    Info : JTAG tap: auto0.tap tap/device found: 0x2b94402f (mfg: 0x017 (Texas Instruments), part: 
    0xb944, ver: 0x2)
    Info : TAP am335x.jrc does not have IDCODE
    Error: am335x.jrc: IR capture error; saw 0x30 not 0x01 
    Warn : Bypassing JTAG setup events due to errors
    Info : Listening on port 3333 for gdb connections
    Info : Listening on port 3334 for gdb connections

**Comment by ilg-ul** [comment]
sorry, I don't use openocd, and I don't have experience with the BB. :-(
